version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: tuanthanh
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: social-network-SNet
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 200mb --maxmemory-policy noeviction
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/index
    networks:
      - app-network
    restart: always

  # backend-fastapi:
  #   build:
  #     context: ./fastapi-ai
  #     dockerfile: Dockerfile
  #   container_name: backend_fastapi
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - chromadb
  #   networks:
  #     - app-network
  #   env_file:
  #     - .env

  # backend-nestjs:
  #   container_name: backend_nestjs
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     # Database
  #     DATABASE_HOST: ${DATABASE_HOST:-postgres}
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     # Redis
  #     REDIS_HOST: ${REDIS_HOST:-redis}
  #     REDIS_PORT: ${REDIS_PORT:-6379}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     REDIS_DB: ${REDIS_DB}
  #     # BullMQ
  #     BULLMQ_HOST: ${BULLMQ_HOST:-redis}
  #     BULLMQ_PORT: ${BULLMQ_PORT:-6379}
  #     BULLMQ_PASSWORD: ${BULLMQ_PASSWORD}
  #     BULLMQ_DB: ${BULLMQ_DB}
  #     # Other
  #     JWT_ACCESS_EXPIRE: ${JWT_ACCESS_EXPIRE}
  #     JWT_REFRESH_EXPIRE: ${JWT_REFRESH_EXPIRE}
  #     JWT_REFRESH_EXPIRE_DAY: ${JWT_REFRESH_EXPIRE_DAY}
  #     THROTTLE_TTL: ${THROTTLE_TTL}
  #     THROTTLE_LIMIT: ${THROTTLE_LIMIT}
  #     NODE_ENV: ${NODE_ENV:-development}
  #     PORT: ${PORT:-3000}
  #   ports:
  #     - '${PORT:-3000}:${PORT:-3000}'
  #   env_file: .env
  #   depends_on:
  #     - postgres
  #     - redis
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #   volumes:
  #     - .:/usr/src/app:cached
  #     - /usr/src/app/node_modules
  #   networks:
  #     - app-network
  #   restart: unless-stopped

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  chromadb_data:
  postgres_data:
  redis_data:
